server:
  port: 8088

spring:
  datasource:
    username: support
    password: Supp0rt
    url: jdbc:mysql://10.144.233.77/db_e
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

satusehat:
  clientId: ZIunZZUyuOpKYbe0rqRNYsRH6lEL9ZQP7l1U4ChRTJDSxhSA
  clientSecret: 0vp7YJbZQE0ygYBI7AaWjvgV7ZRIWj3dRrDdVnbzxwGp6bkUxevAb6YXrMWv5ipT